<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>ISpy</AssemblyName>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <ImplicitUsings>enable</ImplicitUsings>
        <!-- <NoWarn>IDE0010</NoWarn> -->
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <Version>0.5.0</Version>
        <Fileversion>0.5.0.0</Fileversion>
        <Authors>trackd</Authors>
        <Description>PowerShell module for decompiling .NET assemblies using ILSpy decompiler</Description>
    </PropertyGroup>
    <PropertyGroup>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <AnalysisLevel>latest-Recommended</AnalysisLevel>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ICSharpCode.Decompiler" Version="10.1.0.8386" />
        <PackageReference Include="Roslynator.Analyzers" Version="4.*">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.CodeFixes" Version="4.*">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
        <PackageReference Include="System.Management.Automation" Version="7.6" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="all" />
        <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
    </ItemGroup>
</Project>
